### ISSUE TITLE
Failed at [tf-builder 5/6] with "Could not find any cusolver_common.h matching version '' in any subdirectory"

### ISSUE THREAD

**Issue by InkosiZhong** [casys-kaist/CoVA#4]
I have followed README to build up the docker image.
However, the building process crash at [tf-builder 5/6] with error:
``` sh
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
Could not find any cusolver_common.h matching version '' in any subdirectory:
...
```
I have search for the issues related with `cusolver_common.h` on Google and GitHub.
However, the existing problems are not helpful.
### Full Error
``` sh
[tf-builder 5/6] RUN /usr/local/lib/bazel/bin/bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
	Extracting Bazel installation...
	Starting local Bazel server and connecting to it...
	INFO: Options provided by the client:
	Inherited 'common' options: --isatty=0 --terminal_columns=80
	INFO: Reading rc options for 'build' from /build/tf/tensorflow/.bazelrc:
	Inherited 'common' options: --experimental_repo_remote_exec
	INFO: Reading rc options for 'build' from /build/tf/tensorflow/.bazelrc:
	'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
	INFO: Reading rc options for 'build' from /build/tf/tensorflow/.tf_configure.bazelrc:
	'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3.7 --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.7/dist-packages --python_path=/usr/bin/python3.7 --config=tensorrt --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.4 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.6 --action_env LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-7 --config=cuda
	INFO: Reading rc options for 'build' from /build/tf/tensorflow/.bazelrc:
	'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
	INFO: Found applicable config definition build:short_logs in file /build/tf/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
	INFO: Found applicable config definition build:v2 in file /build/tf/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
	INFO: Found applicable config definition build:tensorrt in file /build/tf/tensorflow/.bazelrc: --repo_env TF_NEED_TENSORRT=1
	INFO: Found applicable config definition build:cuda in file /build/tf/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
	INFO: Found applicable config definition build:opt in file /build/tf/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
	INFO: Found applicable config definition build:linux in file /build/tf/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
	INFO: Found applicable config definition build:dynamic_kernels in file /build/tf/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
	WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/c3e082762b7664bbc7ffd2c39e86464928e27c0c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
	INFO: Repository local_config_cuda instantiated at:
	/build/tf/tensorflow/WORKSPACE:15:14: in <toplevel>
	/build/tf/tensorflow/tensorflow/workspace2.bzl:878:19: in workspace
	/build/tf/tensorflow/tensorflow/workspace2.bzl:96:19: in _tf_toolchains
	Repository rule cuda_configure defined at:
	/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl:1448:33: in <toplevel>
	ERROR: An error occurred during the fetch of repository 'local_config_cuda':
	Traceback (most recent call last):
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
	_create_local_cuda_repository(repository_ctx)
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 978, column 35, in _create_local_cuda_repository
	cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 666, column 30, in _get_cuda_config
	config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 643, column 41, in find_cuda_config
	exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 637, column 19, in _exec_find_cuda_config
	return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/build/tf/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
	fail(
	Error in fail: Repository command failed
	Could not find any cusolver_common.h matching version '' in any subdirectory:
	''
	'include'
	'include/cuda'
	'include/*-linux-gnu'
	'extras/CUPTI/include'
	'include/cuda/CUPTI'
	of:
	'/lib'
	'/lib/i386-linux-gnu'
	'/lib/x86_64-linux-gnu'
	'/usr'
	'/usr/lib'
	'/usr/lib/i386-linux-gnu'
	'/usr/lib/x86_64-linux-gnu'
	'/usr/local/cuda'
	'/usr/local/cuda-11/targets/x86_64-linux/lib'
	'/usr/local/cuda/targets/x86_64-linux/lib'
	'/usr/local/lib'
	ERROR: Error fetching repository: Traceback (most recent call last):
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
	_create_local_cuda_repository(repository_ctx)
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 978, column 35, in _create_local_cuda_repository
	cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 666, column 30, in _get_cuda_config
	config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 643, column 41, in find_cuda_config
	exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/build/tf/tensorflow/third_party/gpus/cuda_configure.bzl", line 637, column 19, in _exec_find_cuda_config
	return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/build/tf/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
	fail(
	Error in fail: Repository command failed
	Could not find any cusolver_common.h matching version '' in any subdirectory:
	''
	'include'
	'include/cuda'
	'include/*-linux-gnu'
	'extras/CUPTI/include'
	'include/cuda/CUPTI'
	of:
	'/lib'
	'/lib/i386-linux-gnu'
	'/lib/x86_64-linux-gnu'
	'/usr'
	'/usr/lib'
	'/usr/lib/i386-linux-gnu'
	'/usr/lib/x86_64-linux-gnu'
	'/usr/local/cuda'
	'/usr/local/cuda-11/targets/x86_64-linux/lib'
	'/usr/local/cuda/targets/x86_64-linux/lib'
	'/usr/local/lib'
	INFO: Found applicable config definition build:cuda in file /build/tf/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
	ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
	Could not find any cusolver_common.h matching version '' in any subdirectory:
	''
	'include'
	'include/cuda'
	'include/*-linux-gnu'
	'extras/CUPTI/include'
	'include/cuda/CUPTI'
	of:
	'/lib'
	'/lib/i386-linux-gnu'
	'/lib/x86_64-linux-gnu'
	'/usr'
	'/usr/lib'
	'/usr/lib/i386-linux-gnu'
	'/usr/lib/x86_64-linux-gnu'
	'/usr/local/cuda'
	'/usr/local/cuda-11/targets/x86_64-linux/lib'
	'/usr/local/cuda/targets/x86_64-linux/lib'
	'/usr/local/lib'
	

```
### Environment
RTX 2080Ti GPU
Ubuntu 20.04

**Comment by jinuhwang** [comment]
Hi @InkosiZhong,

Thank you for reaching out and sharing the details of the issue. It seems like the problem could be related to the CUDA configuration within our Docker environment, and using a newer Docker image might resolve this. Unfortunately, I'm currently unable to update these images on my end.

Have you had any luck resolving this issue on your own, or do you have any updates? Any insights you might share could be beneficial for us all.
